[tools]
"github:slsa-framework/slsa-verifier" = "2.7.1"
go = "1.26"

[tasks.build]
run = "go build -o dist/vsync ./cmd/vsync"

[tasks.test]
run = "go test ./..."

[tasks.install]
run = "go install ./cmd/vsync"
